# Generated by Django 5.2 on 2025-06-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachavailability',
            name='last_action',
            field=models.CharField(blank=True, choices=[('CONFIRM', 'Confirmed'), ('DECLINE', 'Declined')], help_text='The last explicit action taken by the coach.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='coachavailability',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the status was explicitly confirmed or declined.', null=True),
        ),
    ]
