# Generated by Django 5.2 on 2025-09-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-session_date', '-session_start_time'], 'permissions': [('can_view_all_sessions', 'Can view all sessions on the calendar')]},
        ),
    ]
