# Generated by Django 5.2 on 2025-06-21 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
        ('scheduling', '0002_coachavailability_last_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ATTENDING', 'Attending'), ('NOT_ATTENDING', 'Not Attending')], default='PENDING', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update.')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='players.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_attendances', to='scheduling.session')),
            ],
            options={
                'verbose_name': 'Player Attendance Tracking',
                'unique_together': {('session', 'player')},
            },
        ),
    ]
