# Generated by Django 5.2 on 2025-06-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_attendancetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='plan',
            field=models.JSONField(blank=True, help_text='Stores the detailed lesson plan including timeline, groups, and activities.', null=True),
        ),
    ]
