# Generated by Django 5.2 on 2025-09-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_rebuild_session_coach_relation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessioncoach',
            options={'verbose_name': 'Session Coach Assignment', 'verbose_name_plural': 'Session Coach Assignments'},
        ),
        migrations.AlterField(
            model_name='sessioncoach',
            name='coaching_duration_minutes',
            field=models.PositiveIntegerField(help_text='The planned duration this coach will be at the session, in minutes.'),
        ),
    ]
