# Generated by Django 5.2 on 2025-07-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_session_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A category or tag for a drill (e.g., Fitness, Forehand, Fun Games).', max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='drill',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='drills', to='scheduling.drilltag'),
        ),
    ]
