# Generated by Django 5.2.8 on 2026-01-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_sessionnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncoach',
            name='is_head_coach',
            field=models.BooleanField(default=False, help_text='Designates if this coach is the Head Coach for the session.'),
        ),
    ]
