# Generated by Django 5.2 on 2025-07-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_drilltag_drill_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='The actual end time when a session is finished.', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='The actual start time when a coach begins the session.', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
    ]
