# Generated by Django 5.2 on 2025-08-11 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_session_end_time_session_start_time_session_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manualcourtassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='manualcourtassignment',
            name='player',
        ),
        migrations.RemoveField(
            model_name='manualcourtassignment',
            name='time_block',
        ),
        migrations.RemoveField(
            model_name='timeblock',
            name='session',
        ),
        migrations.DeleteModel(
            name='ActivityAssignment',
        ),
        migrations.DeleteModel(
            name='ManualCourtAssignment',
        ),
        migrations.DeleteModel(
            name='TimeBlock',
        ),
    ]
