# Generated by Django 5.2.8 on 2026-01-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_sessioncoach_is_head_coach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledclass',
            options={'ordering': ['day_of_week', 'default_venue__name', 'start_time'], 'verbose_name': 'Scheduled Class Rule', 'verbose_name_plural': 'Scheduled Class Rules'},
        ),
    ]
