# Generated by Django 5.2 on 2025-08-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_alter_manualcourtassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancetracking',
            name='status',
        ),
        migrations.AddField(
            model_name='attendancetracking',
            name='attended',
            field=models.CharField(choices=[('UNSET', 'Unset'), ('YES', 'Yes'), ('NO', 'No')], default='UNSET', max_length=10, verbose_name='Coach-Marked Attendance'),
        ),
        migrations.AddField(
            model_name='attendancetracking',
            name='parent_response',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ATTENDING', 'Attending'), ('NOT_ATTENDING', 'Not Attending')], default='PENDING', max_length=20, verbose_name="Parent's Response"),
        ),
    ]
