# Generated by Django 5.2 on 2025-08-20 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_coachavailability_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive routines won't be shown to players.")),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='The order of the drill in the routine (e.g., 1, 2, 3...).')),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.drill')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.routine')),
            ],
            options={
                'ordering': ['routine', 'order'],
                'unique_together': {('routine', 'drill', 'order')},
            },
        ),
        migrations.AddField(
            model_name='routine',
            name='drills',
            field=models.ManyToManyField(related_name='routines', through='scheduling.RoutineDrill', to='scheduling.drill'),
        ),
    ]
