# Generated by Django 5.2 on 2025-08-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_routine_routinedrill_routine_drills'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinedrill',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes for this drill within this specific routine.', null=True),
        ),
    ]
