# Generated by Django 5.2 on 2025-08-23 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive routines won't be shown to players.")),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='The order of the drill in the routine (e.g., 1, 2, 3...).')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration in minutes for this drill within this specific routine.', null=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.drill')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drills_in_routine', to='solosync2.routine')),
            ],
            options={
                'ordering': ['routine', 'order'],
                'unique_together': {('routine', 'drill', 'order')},
            },
        ),
        migrations.AddField(
            model_name='routine',
            name='drills',
            field=models.ManyToManyField(related_name='routines', through='solosync2.RoutineDrill', to='scheduling.drill'),
        ),
        migrations.CreateModel(
            name='SoloSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Actual duration of the solo practice in minutes.')),
                ('exertion_rating', models.PositiveSmallIntegerField(blank=True, help_text="Player's perceived exertion (1-10).", null=True)),
                ('focus_rating', models.PositiveSmallIntegerField(blank=True, help_text="Player's focus level (1-10).", null=True)),
                ('notes', models.TextField(blank=True, help_text="Player's personal notes on the session.", null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_sessions', to='players.player')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solo_sessions', to='solosync2.routine')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
