# Generated by Django 5.2 on 2025-08-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solosync2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinedrill',
            name='rest_duration_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Rest time in seconds after this drill is completed.'),
        ),
    ]
