# Generated by Django 5.2 on 2025-08-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solosync2', '0002_routinedrill_rest_duration_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solosessionlog',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='solosessionlog',
            name='exertion_rating',
        ),
        migrations.RemoveField(
            model_name='solosessionlog',
            name='focus_rating',
        ),
        migrations.AddField(
            model_name='solosessionlog',
            name='difficulty_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Player's perceived difficulty (1-5).", null=True),
        ),
        migrations.AddField(
            model_name='solosessionlog',
            name='likelihood_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Player's likelihood to repeat the routine (1-5).", null=True),
        ),
    ]
