# Generated by Django 5.2 on 2025-06-18 08:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('strengths_observed', models.TextField(blank=True, verbose_name='Strengths Observed')),
                ('areas_for_development', models.TextField(blank=True, verbose_name='Areas for Development')),
                ('suggested_focus', models.TextField(blank=True, verbose_name='Suggested Focus/Next Steps')),
                ('general_notes', models.TextField(blank=True, verbose_name='General Notes')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='players.player')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='scheduling.session')),
            ],
            options={
                'verbose_name': 'Coach Feedback',
                'verbose_name_plural': 'Coach Feedback Entries',
                'ordering': ['-date_recorded', 'player__last_name'],
            },
        ),
        migrations.CreateModel(
            name='GroupAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('general_notes', models.TextField(blank=True, help_text="Coach's notes for the group/session.")),
                ('is_hidden_from_other_coaches', models.BooleanField(default=False, help_text='Hide from other coaches.')),
                ('superuser_reviewed', models.BooleanField(db_index=True, default=False, help_text='Superuser has reviewed this.')),
                ('assessing_coach', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_group_assessments', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assessments', to='scheduling.session')),
            ],
            options={
                'verbose_name': 'Group Assessment',
                'verbose_name_plural': 'Group Assessments',
                'ordering': ['-assessment_datetime', 'session'],
                'unique_together': {('session', 'assessing_coach')},
            },
        ),
        migrations.CreateModel(
            name='SessionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('effort_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('focus_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('resilience_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('composure_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('decision_making_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('coach_notes', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='If true, this assessment is hidden from player/parent view.')),
                ('superuser_reviewed', models.BooleanField(db_index=True, default=False, help_text='Superuser has reviewed this assessment.')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_assessments_by_player', to='players.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_assessments', to='scheduling.session')),
                ('submitted_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_player_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recorded', 'player__last_name'],
                'unique_together': {('session', 'player', 'submitted_by')},
            },
        ),
    ]
