# Generated by Django 5.2 on 2025-08-23 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('strengths_observed', models.TextField(blank=True, verbose_name='Strengths Observed')),
                ('areas_for_development', models.TextField(blank=True, verbose_name='Areas for Development')),
                ('suggested_focus', models.TextField(blank=True, verbose_name='Suggested Focus/Next Steps')),
                ('general_notes', models.TextField(blank=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Coach Feedback',
                'verbose_name_plural': 'Coach Feedback Entries',
                'ordering': ['-date_recorded', 'player__last_name'],
            },
        ),
        migrations.CreateModel(
            name='GroupAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('general_notes', models.TextField(blank=True, help_text="Coach's notes for the group/session.")),
                ('is_hidden_from_other_coaches', models.BooleanField(default=False, help_text='Hide from other coaches.')),
                ('superuser_reviewed', models.BooleanField(db_index=True, default=False, help_text='Superuser has reviewed this.')),
            ],
            options={
                'verbose_name': 'Group Assessment',
                'verbose_name_plural': 'Group Assessments',
                'ordering': ['-assessment_datetime', 'session'],
            },
        ),
        migrations.CreateModel(
            name='SessionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('effort_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('focus_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('resilience_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('composure_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('decision_making_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('coach_notes', models.TextField(blank=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='If true, this assessment is hidden from player/parent view.')),
                ('superuser_reviewed', models.BooleanField(db_index=True, default=False, help_text='Superuser has reviewed this assessment.')),
            ],
            options={
                'ordering': ['-date_recorded', 'player__last_name'],
            },
        ),
    ]
