# Generated by Django 5.2 on 2025-08-23 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('players', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coachfeedback',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='players.player'),
        ),
        migrations.AddField(
            model_name='coachfeedback',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='scheduling.session'),
        ),
        migrations.AddField(
            model_name='groupassessment',
            name='assessing_coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_group_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupassessment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assessments', to='scheduling.session'),
        ),
        migrations.AddField(
            model_name='sessionassessment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_assessments_by_player', to='players.player'),
        ),
        migrations.AddField(
            model_name='sessionassessment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_assessments', to='scheduling.session'),
        ),
        migrations.AddField(
            model_name='sessionassessment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_player_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='groupassessment',
            unique_together={('session', 'assessing_coach')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionassessment',
            unique_together={('session', 'player', 'submitted_by')},
        ),
    ]
