# Generated by Django 5.2 on 2025-09-12 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_comments', to=settings.AUTH_USER_MODEL)),
                ('group_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='assessments.groupassessment')),
                ('session_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='assessments.sessionassessment')),
            ],
            options={
                'verbose_name': 'Assessment Comment',
                'verbose_name_plural': 'Assessment Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
