# Generated by Django 5.2.8 on 2026-01-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionassessment',
            name='composure_rating',
        ),
        migrations.RemoveField(
            model_name='sessionassessment',
            name='decision_making_rating',
        ),
        migrations.RemoveField(
            model_name='sessionassessment',
            name='effort_rating',
        ),
        migrations.RemoveField(
            model_name='sessionassessment',
            name='focus_rating',
        ),
        migrations.RemoveField(
            model_name='sessionassessment',
            name='resilience_rating',
        ),
        migrations.AddField(
            model_name='sessionassessment',
            name='effort_enthusiasm_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True, verbose_name='Effort / Enthusiasm'),
        ),
        migrations.AddField(
            model_name='sessionassessment',
            name='fitness_perseverance_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True, verbose_name='Fitness / Perseverance'),
        ),
        migrations.AddField(
            model_name='sessionassessment',
            name='skill_technique_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True, verbose_name='Skill / Technique'),
        ),
        migrations.AddField(
            model_name='sessionassessment',
            name='sportsmanship_attitude_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True, verbose_name='Sportsmanship / Attitude'),
        ),
        migrations.AddField(
            model_name='sessionassessment',
            name='tactical_mental_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True, verbose_name='Tactical / Mental'),
        ),
    ]
