# Generated by Django 5.2 on 2025-08-23 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='payslips/%Y/%m/')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'coach__name'],
            },
        ),
        migrations.CreateModel(
            name='CoachSessionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessments_submitted', models.BooleanField(default=False, help_text='Coach has submitted all required player assessments.')),
                ('confirmed_for_payment', models.BooleanField(default=False, help_text='Admin has verified and confirmed for payment.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_completions', to='accounts.coach')),
            ],
            options={
                'verbose_name': 'Coach Session Completion',
                'verbose_name_plural': 'Coach Session Completions',
                'ordering': ['session__session_date', 'session__session_start_time', 'coach__name'],
            },
        ),
    ]
