# Generated by Django 5.2 on 2025-06-18 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachSessionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessments_submitted', models.BooleanField(default=False, help_text='Coach has submitted all required player assessments.')),
                ('confirmed_for_payment', models.BooleanField(default=False, help_text='Admin has verified and confirmed for payment.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_completions', to='accounts.coach')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_completions', to='scheduling.session')),
            ],
            options={
                'verbose_name': 'Coach Session Completion',
                'verbose_name_plural': 'Coach Session Completions',
                'ordering': ['session__session_date', 'session__session_start_time', 'coach__name'],
                'unique_together': {('coach', 'session')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='payslips/%Y/%m/')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='accounts.coach')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips_initiated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'coach__name'],
                'unique_together': {('coach', 'month', 'year')},
            },
        ),
    ]
