# Generated by Django 5.2 on 2025-10-30 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_coachinvitation'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringCoachAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Reason for the adjustment (e.g., IT Work, Newsletter Bonus).', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount to be added (positive) or deducted (negative).', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Only active adjustments will be applied to payslips.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_adjustments', to='accounts.coach')),
            ],
            options={
                'verbose_name': 'Recurring Coach Adjustment',
                'verbose_name_plural': 'Recurring Coach Adjustments',
                'ordering': ['-is_active', '-updated_at', 'description'],
            },
        ),
    ]
