# Generated by Django 5.2 on 2025-08-23 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coachsessioncompletion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_completions', to='scheduling.session'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='accounts.coach'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips_initiated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='coachsessioncompletion',
            unique_together={('coach', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('coach', 'month', 'year')},
        ),
    ]
