# Generated by Django 5.2 on 2025-06-18 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text="Coach's hourly rate for payment.", max_digits=6, null=True)),
                ('whatsapp_phone_number', models.CharField(blank=True, help_text='WhatsApp enabled phone number in E.164 format (e.g., +14155238886).', max_length=20, null=True)),
                ('whatsapp_opt_in', models.BooleanField(default=False, help_text='Has the coach opted-in to receive WhatsApp notifications?')),
                ('receive_weekly_schedule_email', models.BooleanField(default=True, help_text='If checked, this coach will receive the weekly schedule summary email every Sunday.', verbose_name='Receive Weekly Schedule Email')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='coach_photos/', verbose_name='Profile Photo')),
                ('experience_notes', models.TextField(blank=True, help_text='Brief notes on coaching experience, specializations, etc.', null=True, verbose_name='Coaching Experience')),
                ('qualification_wsf_level', models.CharField(blank=True, choices=[('NONE', 'None / Not Applicable'), ('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3'), ('OTH', 'Other')], default='NONE', help_text='World Squash Federation coaching qualification level.', max_length=5, verbose_name='WSF Qualification Level')),
                ('qualification_ssa_level', models.CharField(blank=True, choices=[('NONE', 'None / Not Applicable'), ('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3'), ('OTH', 'Other')], default='NONE', help_text='Squash South Africa coaching qualification level.', max_length=5, verbose_name='SSA Qualification Level')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Coaches',
                'ordering': ['name'],
            },
        ),
    ]
