# Generated by Django 5.2.8 on 2026-01-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_coachinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='academic_credentials',
            field=models.TextField(blank=True, verbose_name='Academic & Professional Credentials'),
        ),
        migrations.AddField(
            model_name='coach',
            name='accepts_private_coaching',
            field=models.BooleanField(default=False, verbose_name='Available for One-on-One Coaching?'),
        ),
        migrations.AddField(
            model_name='coach',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('UNK', 'Unknown')], default='UNK', max_length=5, verbose_name='Blood Type'),
        ),
        migrations.AddField(
            model_name='coach',
            name='car_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Car Color'),
        ),
        migrations.AddField(
            model_name='coach',
            name='car_make_model',
            field=models.CharField(blank=True, help_text='e.g. Kia Picanto', max_length=100, verbose_name='Car Make & Model'),
        ),
        migrations.AddField(
            model_name='coach',
            name='car_registration_numbers',
            field=models.CharField(blank=True, help_text='If multiple, separate with commas.', max_length=255, verbose_name='Car Registration Number(s)'),
        ),
        migrations.AddField(
            model_name='coach',
            name='currently_studying',
            field=models.CharField(blank=True, help_text='If student, what are you studying?', max_length=255, verbose_name='Current Studies'),
        ),
        migrations.AddField(
            model_name='coach',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='coach',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Person & Relationship'),
        ),
        migrations.AddField(
            model_name='coach',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Number'),
        ),
        migrations.AddField(
            model_name='coach',
            name='highest_ranking',
            field=models.CharField(blank=True, help_text='World, Provincial, or Club ranking', max_length=255, verbose_name='Highest Squash Ranking'),
        ),
        migrations.AddField(
            model_name='coach',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID Number / DOB'),
        ),
        migrations.AddField(
            model_name='coach',
            name='league_participation',
            field=models.CharField(blank=True, help_text="e.g. Men's League at [Club Name]", max_length=255, verbose_name='League Participation'),
        ),
        migrations.AddField(
            model_name='coach',
            name='medical_aid_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Medical Aid Name'),
        ),
        migrations.AddField(
            model_name='coach',
            name='medical_aid_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Medical Aid Number'),
        ),
        migrations.AddField(
            model_name='coach',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Any conditions we should be aware of (optional).', verbose_name='Medical Conditions'),
        ),
        migrations.AddField(
            model_name='coach',
            name='occupation',
            field=models.CharField(blank=True, help_text='What kind of work do you do and in what area?', max_length=255, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='coach',
            name='physical_address',
            field=models.TextField(blank=True, verbose_name='Physical Address'),
        ),
        migrations.AddField(
            model_name='coach',
            name='private_coaching_area',
            field=models.TextField(blank=True, help_text='Preferred area or club.', verbose_name='Private Coaching Area'),
        ),
        migrations.AddField(
            model_name='coach',
            name='private_coaching_preferences',
            field=models.TextField(blank=True, help_text='Preferred age group or skill level.', verbose_name='Private Coaching Preferences'),
        ),
        migrations.AddField(
            model_name='coach',
            name='shirt_preference',
            field=models.CharField(blank=True, choices=[('GOLF', 'Golf Shirt'), ('TEE', 'T-Shirt'), ('NONE', 'No Preference')], default='NONE', max_length=10, verbose_name='T-Shirt Preference'),
        ),
        migrations.AddField(
            model_name='coach',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('L_XS', 'Ladies XS'), ('L_S', 'Ladies S'), ('L_M', 'Ladies M'), ('L_L', 'Ladies L'), ('L_XL', 'Ladies XL'), ('M_S', 'Mens S'), ('M_M', 'Mens M'), ('M_L', 'Mens L'), ('M_XL', 'Mens XL'), ('M_XXL', 'Mens XXL')], max_length=10, verbose_name='T-Shirt Size'),
        ),
    ]
