# Generated by Django 5.2.8 on 2026-01-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_coach_academic_credentials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='whatsapp_opt_in',
        ),
    ]
