# Generated by Django 5.2.8 on 2026-01-16 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_coach_whatsapp_opt_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. '2026 Service Agreement'", max_length=100)),
                ('content', models.TextField(help_text='Master text with placeholders if needed.')),
                ('is_active', models.BooleanField(default=False, help_text='Only one template should be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoachContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customized_content', models.TextField(help_text='Specific contract text for this coach.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (Admin Editing)'), ('AWAITING_SIGNATURE', 'Awaiting Signature'), ('SIGNED', 'Signed')], default='DRAFT', max_length=20)),
                ('date_signed', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.coach')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.contracttemplate')),
            ],
            options={
                'unique_together': {('coach', 'template')},
            },
        ),
    ]
