# Generated by Django 5.2.8 on 2026-01-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contracttemplate_coachcontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachcontract',
            name='customized_content',
            field=models.TextField(blank=True, help_text='Specific contract text for this coach.'),
        ),
    ]
