# Generated by Django 5.2.8 on 2026-01-31 05:43

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_coachcontract_customized_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='account_number',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=100, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='coach',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Current', 'Current / Cheque'), ('Savings', 'Savings')], default='Current', max_length=20, verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='coach',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='coach',
            name='branch_code',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=20, verbose_name='Branch Code'),
        ),
        migrations.AddField(
            model_name='coach',
            name='xero_contact_id',
            field=models.CharField(blank=True, help_text='Linked Xero contact for payments.', max_length=100, verbose_name='Xero Contact ID'),
        ),
    ]
