# Generated by Django 5.2.8 on 2026-01-31 05:51

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_coach_account_number_coach_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='account_number',
            field=accounts.models.SecureEncryptedCharField(blank=True, max_length=100, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='branch_code',
            field=accounts.models.SecureEncryptedCharField(blank=True, max_length=20, verbose_name='Branch Code'),
        ),
    ]
