# Generated by Django 5.2.8 on 2026-01-31 06:02

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_coach_account_number_alter_coach_branch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='account_number',
            field=accounts.models.SecureEncryptedCharField(blank=True, max_length=255, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='branch_code',
            field=accounts.models.SecureEncryptedCharField(blank=True, max_length=255, verbose_name='Branch Code'),
        ),
    ]
