# Generated by Django 5.2.8 on 2026-01-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_coach_account_number_alter_coach_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text='e.g. Mr J Smith or Company Name', max_length=100, verbose_name='Account Holder Name'),
        ),
    ]
