# finance/admin.py
from django.contrib import admin
from .models import CoachSessionCompletion, Payslip

@admin.register(CoachSessionCompletion)
class CoachSessionCompletionAdmin(admin.ModelAdmin):
    list_display = ('coach', 'session', 'assessments_submitted', 'confirmed_for_payment')
    list_filter = ('session__session_date', 'coach__name', 'assessments_submitted', 'confirmed_for_payment')
    search_fields = ('coach__name',)
    raw_id_fields = ('coach', 'session')

@admin.register(Payslip)
class PayslipAdmin(admin.ModelAdmin):
    list_display = ('__str__', 'coach', 'month', 'year', 'total_amount', 'generated_at')
    list_filter = ('year', 'month', 'coach')
    search_fields = ('coach__name', 'year')
    readonly_fields = ('coach', 'month', 'year', 'total_amount', 'generated_at', 'generated_by', 'file')

    def has_add_permission(self, request):
        return False # Payslips should be generated by actions, not added manually