# Generated by Django 5.2.8 on 2025-12-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drill',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='drill',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='drill',
            name='default_duration',
            field=models.PositiveIntegerField(default=180, help_text='Duration in seconds (deprecated)'),
        ),
    ]
