# Generated by Django 5.2.8 on 2025-12-15 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_coachinvitation'),
        ('live_session', '0002_drill_description_drill_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The coach who created this custom drill.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drills', to='accounts.coach'),
        ),
        migrations.AddField(
            model_name='drill',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='If False, only the creator can see this drill.'),
        ),
    ]
