# Generated by Django 5.2.8 on 2026-01-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_session', '0003_drill_created_by_drill_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='category',
            field=models.CharField(choices=[('Conditioning', 'Conditioning'), ('Warmups', 'Warmups'), ('Hand-Eye Coordination', 'Hand-Eye Coordination'), ('Fun Games', 'Fun Games'), ('Ghosting', 'Ghosting'), ('Drills - Racketwork', 'Drills - Racketwork'), ('Feeding Drills', 'Feeding Drills'), ('Condition Games', 'Condition Games'), ('Fitness', 'Fitness'), ('Movement', 'Movement'), ('Circuits (Score/Time)', 'Circuits (Score/Time)')], max_length=50),
        ),
    ]
