# Generated by Django 5.2.8 on 2026-01-20 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_coachcontract_customized_content'),
        ('live_session', '0004_alter_drill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Visible to all coaches')),
                ('court_count', models.PositiveIntegerField(default=3, help_text='Number of courts this plan was designed for')),
                ('plan_data', models.JSONField(help_text='The full courtPlans JSON structure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.coach')),
            ],
        ),
    ]
