# Generated by Django 5.2.8 on 2026-01-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_session', '0005_plantemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='equipment',
            field=models.CharField(blank=True, help_text="Equipment needed for this drill (e.g. 'Cones', 'Target Board')", max_length=200),
        ),
    ]
