# Generated by Django 5.2.8 on 2026-01-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_session', '0006_drill_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='resource_text',
            field=models.TextField(blank=True, help_text='Text content for rules, marking guides, etc.'),
        ),
        migrations.AddField(
            model_name='drill',
            name='resource_url',
            field=models.URLField(blank=True, help_text='Link to external document (e.g., Google Drive)', null=True),
        ),
        migrations.AlterField(
            model_name='drill',
            name='category',
            field=models.CharField(choices=[('Conditioning', 'Conditioning'), ('Warmups', 'Warmups'), ('Hand-Eye Coordination', 'Hand-Eye Coordination'), ('Fun Games', 'Fun Games'), ('Ghosting', 'Ghosting'), ('Drills - Racketwork', 'Drills - Racketwork'), ('Feeding Drills', 'Feeding Drills'), ('Condition Games', 'Condition Games'), ('Fitness', 'Fitness'), ('Movement', 'Movement'), ('Circuits (Score/Time)', 'Circuits (Score/Time)'), ('Squash Basics', 'Squash Basics')], max_length=50),
        ),
    ]
