# Generated by Django 5.2 on 2025-06-18 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backwalldriverecord',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to session where this test was conducted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_tests_conducted', to='scheduling.session'),
        ),
        migrations.AddField(
            model_name='courtsprintrecord',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to session where this test was conducted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_tests_conducted', to='scheduling.session'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to session if this match was part of it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_played', to='scheduling.session'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='players.player'),
        ),
        migrations.AddField(
            model_name='courtsprintrecord',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_records', to='players.player'),
        ),
        migrations.AddField(
            model_name='backwalldriverecord',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_records', to='players.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='school_groups',
            field=models.ManyToManyField(blank=True, related_name='players', to='players.schoolgroup'),
        ),
        migrations.AddField(
            model_name='volleyrecord',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volley_records', to='players.player'),
        ),
        migrations.AddField(
            model_name='volleyrecord',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to session where this test was conducted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volley_tests_conducted', to='scheduling.session'),
        ),
    ]
