# Generated by Django 5.2 on 2025-06-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='The primary email for parent communication.', max_length=254, null=True),
        ),
    ]
