# Generated by Django 5.2 on 2025-09-02 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='opponent',
            field=models.ForeignKey(blank=True, help_text='The player who was the opponent. Null if the opponent is not a registered player.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_matches', to='players.player'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='opponent_name',
            field=models.CharField(blank=True, help_text='Use this if the opponent is not a registered player.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='players.player'),
        ),
    ]
