# Generated by Django 5.2 on 2025-08-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_parent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='skill_level',
        ),
    ]
