# Generated by Django 5.2 on 2025-08-11 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_player_skill_level'),
        ('scheduling', '0008_remove_attendancetracking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy_type', models.CharField(choices=[('NO_SHOW', 'No-Show'), ('UNEXPECTED', 'Unexpected'), ('NEVER_NOTIFIED', 'Never Notified')], max_length=20)),
                ('parent_response', models.CharField(max_length=20)),
                ('coach_marked_attendance', models.CharField(max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_discrepancies', to='players.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_discrepancies', to='scheduling.session')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'unique_together': {('player', 'session')},
            },
        ),
    ]
