# Generated by Django 5.2 on 2025-09-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolgroup',
            options={'ordering': ['name'], 'permissions': [('can_manage_school_groups', 'Can manage school groups')]},
        ),
    ]
