# Generated by Django 5.2 on 2025-08-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_attendancediscrepancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancediscrepancy',
            name='admin_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
