# Generated by Django 5.2 on 2025-10-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_schoolgroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Prefer not to say'), ('U', 'Unspecified')], default='U', max_length=1, null=True, verbose_name='Gender'),
        ),
    ]
