# Generated by Django 5.2 on 2025-08-20 04:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_attendancediscrepancy_admin_acknowledged'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='submitted_by_name',
            field=models.CharField(blank=True, help_text='Name of the person who submitted the score from the app.', max_length=100),
        ),
        migrations.CreateModel(
            name='SoloPracticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of the solo practice in minutes.')),
                ('notes', models.TextField(blank=True, help_text="Player's personal notes on the session.", null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_logs', to='players.player')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
