# Generated by Django 5.2.8 on 2026-01-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_player_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='guardian_2_contact_number',
            field=models.CharField(blank=True, help_text='Enter number including country code.', max_length=20, verbose_name='Secondary Guardian Contact Number'),
        ),
        migrations.AddField(
            model_name='player',
            name='guardian_2_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Secondary Guardian Email'),
        ),
        migrations.AddField(
            model_name='player',
            name='guardian_2_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Secondary Guardian Name'),
        ),
        migrations.AddField(
            model_name='player',
            name='health_information',
            field=models.TextField(blank=True, help_text='Allergies, illnesses, or specific medical conditions.', verbose_name='Health Information'),
        ),
        migrations.AddField(
            model_name='player',
            name='medical_aid_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Medical Aid Number'),
        ),
        migrations.AlterField(
            model_name='player',
            name='parent_contact_number',
            field=models.CharField(blank=True, help_text='Primary contact for session reminders. Enter number including country code if outside SA (e.g., +44... or 082...)', max_length=20, verbose_name='Primary Guardian Contact Number'),
        ),
        migrations.AlterField(
            model_name='player',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='The primary email for parent communication and session reminders.', max_length=254, null=True, verbose_name='Primary Guardian Email'),
        ),
    ]
