# Generated by Django 5.2.8 on 2026-01-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_player_guardian_2_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolgroup',
            options={'ordering': ['-is_active', 'name'], 'permissions': [('can_manage_school_groups', 'Can manage school groups')]},
        ),
        migrations.AddField(
            model_name='schoolgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolgroup',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
