# Generated by Django 5.2.8 on 2026-01-27 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_alter_schoolgroup_options_schoolgroup_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='sets_data',
            field=models.JSONField(blank=True, help_text="List of set scores, e.g. [{'p1': 11, 'p2': 9}, ...]", null=True),
        ),
    ]
