# Generated by Django 5.2.8 on 2026-01-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_matchresult_created_by_matchresult_sets_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Verified email address for session reminders and player notifications.', max_length=254, null=True, verbose_name='Notification Email'),
        ),
    ]
