# Generated by Django 5.2.8 on 2026-01-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_player_notification_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Verified email address for session reminders.', max_length=254, null=True, verbose_name='Player Notification Email'),
        ),
    ]
