# Generated by Django 5.2 on 2025-10-25 04:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0005_alter_schoolgroup_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Prize Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(default=2025, help_text='The year this prize instance is for.')),
                ('min_grade', models.IntegerField(blank=True, choices=[(0, 'Grade R'), (1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12 (Matric)'), (99, 'Other / Not Applicable')], help_text='Minimum grade to be eligible (inclusive).', null=True)),
                ('max_grade', models.IntegerField(blank=True, choices=[(0, 'Grade R'), (1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12 (Matric)'), (99, 'Other / Not Applicable')], help_text='Maximum grade to be eligible (inclusive).', null=True)),
                ('voting_start_date', models.DateField(blank=True, null=True)),
                ('voting_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('VOTING', 'Voting Open'), ('DECIDED', 'Decided'), ('ARCHIVED', 'Archived')], default='VOTING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='awards.prizecategory')),
            ],
            options={
                'ordering': ['-year', 'category__name', 'name'],
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PrizeWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateField(default=django.utils.timezone.now)),
                ('awarded_by', models.ForeignKey(limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_prizes', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes_won', to='players.player')),
                ('prize', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner_details', to='awards.prize')),
            ],
            options={
                'ordering': ['-prize__year', 'prize__category__name', 'prize__name'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(choices=[(1, '1st Choice'), (2, '2nd Choice'), (3, '3rd Choice')])),
                ('comment', models.TextField(blank=True, help_text='Optional comment explaining the vote.', null=True)),
                ('voted_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_votes', to='players.player')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='awards.prize')),
                ('voter', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='cast_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prize', 'player', 'rank'],
                'unique_together': {('prize', 'player', 'voter'), ('prize', 'voter', 'rank')},
            },
        ),
    ]
