# Generated by Django 5.2 on 2025-10-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='gender_eligibility',
            field=models.CharField(choices=[('A', 'Any Gender'), ('M', 'Male Only'), ('F', 'Female Only')], default='A', help_text='Which gender(s) are eligible for this prize?', max_length=1),
        ),
    ]
