# Generated by Django 5.2 on 2025-10-25 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
        ('players', '0005_alter_schoolgroup_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prizewinner',
            options={'ordering': ['-year', 'prize__category__name', 'prize__name']},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['prize', 'player', 'voter', 'voted_at']},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('prize', 'player', 'voter')},
        ),
        migrations.AddField(
            model_name='prize',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_prize_direct', to='awards.prizewinner'),
        ),
        migrations.AddField(
            model_name='prizewinner',
            name='final_score',
            field=models.IntegerField(blank=True, help_text="The winner's final vote count at time of awarding.", null=True),
        ),
        migrations.AddField(
            model_name='prizewinner',
            name='year',
            field=models.PositiveIntegerField(default=2025, editable=False, help_text='The year the prize was awarded.'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='cast_prize_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='prizewinner',
            unique_together={('prize', 'year')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='rank',
        ),
    ]
