# Generated by Django 5.2.8 on 2026-01-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_prize_gender_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
